#ifndef TEM_VERSION_H
#define TEM_VERSION_H

#define TEM_VERSION_MAJOR 0
#define TEM_VERSION_MINOR 1
#define TEM_VERSION_PATCH 0

#define TEM_VERSION #TEM_VERSION_MAJOR "." #TEM_VERSION_MINOR "." #TEM_VERSION_PATCH

#endif // !TEM_VERSION
